# Generated by Django 5.0.4 on 2024-05-04 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation_engine", "0002_alter_approvalqueue_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalqueue",
            options={
                "ordering": ("node__approval_step__forward_step",),
                "verbose_name": "Approval Queue",
                "verbose_name_plural": "Approval Queues",
            },
        ),
    ]
