# Generated by Django 5.0.4 on 2024-05-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendation_engine", "0003_alter_approvalqueue_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalqueue",
            name="status",
            field=models.CharField(
                choices=[
                    ("init", "Init"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("archived", "Archived"),
                    ("not_required", "Not Required"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
