# Generated by Django 5.0.3 on 2024-03-23 04:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import pms.models.party_attachment


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codename",
                    models.CharField(max_length=255, verbose_name="Code Name"),
                ),
                (
                    "viewname",
                    models.CharField(max_length=255, verbose_name="View Name"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active ?"),
                ),
                (
                    "parent_id",
                    models.IntegerField(
                        blank=True, default=None, null=True, verbose_name="Parent ID"
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        choices=[("image", "IMAGE"), ("pdf", "PDF"), ("any", "ANY")],
                        default="pdf",
                        max_length=255,
                        verbose_name="Extension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment Repository",
                "verbose_name_plural": "🗃️ Attachment Repositories",
                "db_table": "pms_attachment_repository",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=99, verbose_name="Authorized Contact Person"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                (
                    "pp_photo_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="attachments/",
                        verbose_name="Passport Size Photo",
                    ),
                ),
                (
                    "vcard_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="attachments/contacts",
                        verbose_name="Visiting Card",
                    ),
                ),
                (
                    "vcard_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="vCard Number",
                    ),
                ),
                (
                    "ecard_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="attachments/contacts",
                        verbose_name="Employee Card",
                    ),
                ),
                (
                    "ecard_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="EmployeeID Number",
                    ),
                ),
                (
                    "nid_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="attachments/contacts",
                        verbose_name="National Identification Card",
                    ),
                ),
                (
                    "nid_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="NID Number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Person",
                "verbose_name_plural": "📤 Contact Person's",
                "db_table": "pms_contact_person",
            },
        ),
        migrations.CreateModel(
            name="CreditLimitDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "org_type",
                    models.CharField(
                        blank=True,
                        choices=[("wdc", "WDC"), ("wcl", "WCL")],
                        default=None,
                        max_length=30,
                        null=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=34)),
                (
                    "micr_cheque",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="credit_limit_applications/",
                        verbose_name="MICR Cheque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Limit Application Detail",
                "verbose_name_plural": "📤 Credit Limit Application Details",
                "db_table": "pms_credit_limit_application_detail",
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "witp_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="WITP Code"
                    ),
                ),
                (
                    "party_name",
                    models.CharField(max_length=255, verbose_name="Party Name"),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=99, verbose_name="Owner Name"),
                ),
                (
                    "trade_license_expires",
                    models.DateField(verbose_name="Trade License Expires"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "factory_distance",
                    models.CharField(
                        choices=[
                            ("0_99", "0-99 KM"),
                            ("100_199", "100-199 KM"),
                            ("200_299", "200-299 KM"),
                            ("300_UP", "300-Above KM"),
                        ],
                        default="0_99",
                        max_length=255,
                        verbose_name="Factory Distance (Km)",
                    ),
                ),
                (
                    "transaction_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("credit", "Credit"),
                            ("partial_payment", "Partial Payment"),
                        ],
                        default="cash",
                        max_length=99,
                        verbose_name="Transaction Method",
                    ),
                ),
                (
                    "party_present_addr",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Party Present Address",
                    ),
                ),
                ("stepper_index", models.IntegerField(default=0)),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("incharge", "Incharge"),
                            ("credit_monitoring", "Credit Monitoring"),
                            ("logistics", "Logistic & Order Management"),
                            ("cbo", "Chief Business Officer"),
                            ("amd", "Additional Managing Director"),
                            ("chairman", "Honorable Chairman"),
                            ("ebs", "EBS"),
                            ("approved", "Approved"),
                        ],
                        default=None,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending"),
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("not_required", "Not Required"),
                        ],
                        default="draft",
                        max_length=255,
                    ),
                ),
                (
                    "trade_license",
                    models.CharField(max_length=255, verbose_name="Trade License"),
                ),
                (
                    "trade_license_file",
                    models.FileField(
                        upload_to="attachments/party", verbose_name="Trade License"
                    ),
                ),
                (
                    "bin_number",
                    models.CharField(max_length=255, verbose_name="VAT/BIN Number"),
                ),
                (
                    "bin_number_file",
                    models.FileField(
                        upload_to="attachments/party",
                        verbose_name="Business Identification Numbers",
                    ),
                ),
                (
                    "tin_number",
                    models.CharField(max_length=255, verbose_name="TIN Number"),
                ),
                (
                    "tin_number_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="attachments/party",
                        verbose_name="Taxpayer Identification Numbers",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Party",
                "verbose_name_plural": "🏫 Parties",
                "db_table": "pms_party",
            },
        ),
        migrations.CreateModel(
            name="PartyAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_authorization_letter",
                    models.FileField(
                        upload_to=pms.models.party_attachment.upload_to_dir
                    ),
                ),
                (
                    "party_authorization_letter_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "incorporation_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=pms.models.party_attachment.upload_to_dir,
                    ),
                ),
                (
                    "incorporation_certificate_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=pms.models.party_attachment.upload_to_dir,
                    ),
                ),
                (
                    "payment_receipt_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bank_solvency",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=pms.models.party_attachment.upload_to_dir,
                    ),
                ),
                (
                    "bank_solvency_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "security_cheque",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=pms.models.party_attachment.upload_to_dir,
                    ),
                ),
                (
                    "security_cheque_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "other_1",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=pms.models.party_attachment.upload_to_dir,
                    ),
                ),
                (
                    "other_1_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "other_2",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=pms.models.party_attachment.upload_to_dir,
                    ),
                ),
                (
                    "other_2_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "other_3",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=pms.models.party_attachment.upload_to_dir,
                    ),
                ),
                (
                    "other_3_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Party Attachment",
                "verbose_name_plural": "📦 Party Attachment's",
                "db_table": "pms_party_attachment",
            },
        ),
        migrations.CreateModel(
            name="PartyDealing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mou",
                    models.CharField(
                        blank=True,
                        max_length=99,
                        null=True,
                        verbose_name="MOU/PO/NOA/RFQ",
                    ),
                ),
                (
                    "mou_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="attachments/party_dealing",
                        verbose_name="MOU/RFQ/NOA/PO/WO File",
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Remarks"
                    ),
                ),
            ],
            options={
                "verbose_name": "Party Dealing",
                "verbose_name_plural": "📜 Party Dealings",
                "db_table": "pms_dealing_information",
            },
        ),
        migrations.CreateModel(
            name="SecurityCheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cheque_number",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=99,
                        null=True,
                        verbose_name="Security Check / BG Number",
                    ),
                ),
                (
                    "cheque_amount",
                    models.FloatField(default=0, verbose_name="Security cheque Amount"),
                ),
                (
                    "cheque_file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="attachments/party_dealing",
                        verbose_name="Security Cheque Image",
                    ),
                ),
                (
                    "cheque_issue_date",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="Issue Date"
                    ),
                ),
                (
                    "cheque_maturity_date",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Maturity Date",
                    ),
                ),
                (
                    "account_of",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=99,
                        null=True,
                        verbose_name="Account Of",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Cheque",
                "verbose_name_plural": "📜 Security Cheque",
                "db_table": "pms_security_cheque",
            },
        ),
        migrations.CreateModel(
            name="ShipLocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("witp_code", models.CharField(max_length=255)),
                ("party_name", models.CharField(max_length=255)),
                (
                    "recommended_delivery_addr",
                    models.TextField(verbose_name="Recommended Delivery Address"),
                ),
                (
                    "receiver_name",
                    models.CharField(max_length=255, verbose_name="Receiver Name"),
                ),
                (
                    "receiver_number",
                    models.CharField(max_length=20, verbose_name="Receiver Number"),
                ),
                (
                    "factory_distance",
                    models.CharField(
                        choices=[
                            ("0_99", "0-99 KM"),
                            ("100_199", "100-199 KM"),
                            ("200_299", "200-299 KM"),
                            ("300_UP", "300-Above KM"),
                        ],
                        max_length=255,
                        verbose_name="Factory Distance",
                    ),
                ),
                (
                    "wo_po_mou_reference",
                    models.CharField(
                        max_length=255, verbose_name="WO/PO/NOA/RFQ/MOU/Any Reference"
                    ),
                ),
                (
                    "wo_po_mou_attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ship_location_applications/",
                        verbose_name="WO/PO/NOA/RFQ/MOU/Any Attachment",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("incharge", "Incharge"),
                            ("credit_monitoring", "Credit Monitoring"),
                            ("logistics", "Logistic & Order Management"),
                            ("cbo", "Chief Business Officer"),
                            ("amd", "Additional Managing Director"),
                            ("chairman", "Honorable Chairman"),
                            ("ebs", "EBS"),
                            ("approved", "Approved"),
                        ],
                        default=None,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending"),
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("not_required", "Not Required"),
                        ],
                        default="submitted",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ship Location Application",
                "verbose_name_plural": "🚢 Ship Location Applications",
                "db_table": "pms_ship_location_application",
            },
        ),
        migrations.CreateModel(
            name="CreditLimit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("witp_code", models.CharField(max_length=255)),
                ("party_name", models.CharField(max_length=255)),
                (
                    "proposed_limit_wdc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=34,
                        null=True,
                        verbose_name="Proposed Limit WDC",
                    ),
                ),
                (
                    "proposed_limit_wcl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=34,
                        null=True,
                        verbose_name="Proposed Limit WCL",
                    ),
                ),
                (
                    "approved_limit_wdc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=34,
                        null=True,
                        verbose_name="Approved Limit WDC",
                    ),
                ),
                (
                    "approved_limit_wcl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=34,
                        null=True,
                        verbose_name="Approved Limit WCL",
                    ),
                ),
                (
                    "wo_po_mou",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="credit_limit_applications/",
                        verbose_name="WO/PO/NOA/RFQ/MOU",
                    ),
                ),
                (
                    "rating_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="credit_limit_applications/",
                        verbose_name="Rating Certificate",
                    ),
                ),
                (
                    "updated_ledger_wdc",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="credit_limit_applications/",
                        verbose_name="Updated Ledger WDC",
                    ),
                ),
                (
                    "updated_ledger_wcl",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="credit_limit_applications/",
                        verbose_name="Updated Ledger WCL",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("incharge", "Incharge"),
                            ("credit_monitoring", "Credit Monitoring"),
                            ("logistics", "Logistic & Order Management"),
                            ("cbo", "Chief Business Officer"),
                            ("amd", "Additional Managing Director"),
                            ("chairman", "Honorable Chairman"),
                            ("ebs", "EBS"),
                            ("approved", "Approved"),
                        ],
                        default=None,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending"),
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("not_required", "Not Required"),
                        ],
                        default="draft",
                        max_length=255,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_by_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Limit Application",
                "verbose_name_plural": "📤 Credit Limit Applications",
                "db_table": "pms_credit_limit_application",
            },
        ),
    ]
