# Generated by Django 5.0.3 on 2024-04-01 09:21

import django.db.models.deletion
from django.db import migrations, models

import pms.models.party_attachment


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partyattachment",
            name="other_1",
        ),
        migrations.RemoveField(
            model_name="partyattachment",
            name="other_1_desc",
        ),
        migrations.RemoveField(
            model_name="partyattachment",
            name="other_2",
        ),
        migrations.RemoveField(
            model_name="partyattachment",
            name="other_2_desc",
        ),
        migrations.RemoveField(
            model_name="partyattachment",
            name="other_3",
        ),
        migrations.RemoveField(
            model_name="partyattachment",
            name="other_3_desc",
        ),
        migrations.CreateModel(
            name="ExtraAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=pms.models.party_attachment.upload_to_dir
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras",
                        to="pms.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extra Attachment",
                "verbose_name_plural": "Extra Attachments",
                "db_table": "pms_extra_attachments",
            },
        ),
    ]
