# Generated by Django 5.0.3 on 2024-04-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0003_remove_partyattachment_other_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_existing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="extraattachment",
            name="is_existing",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="creditlimit",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("incharge", "Incharge"),
                    ("credit_monitoring", "Credit Monitoring"),
                    ("logistics", "Logistic & Order Management"),
                    ("cbo", "Chief Business Officer"),
                    ("amd", "Additional Managing Director"),
                    ("chairman", "Honorable Chairman"),
                    ("ebs", "EBS"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("incharge", "Incharge"),
                    ("credit_monitoring", "Credit Monitoring"),
                    ("logistics", "Logistic & Order Management"),
                    ("cbo", "Chief Business Officer"),
                    ("amd", "Additional Managing Director"),
                    ("chairman", "Honorable Chairman"),
                    ("ebs", "EBS"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shiplocation",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("incharge", "Incharge"),
                    ("credit_monitoring", "Credit Monitoring"),
                    ("logistics", "Logistic & Order Management"),
                    ("cbo", "Chief Business Officer"),
                    ("amd", "Additional Managing Director"),
                    ("chairman", "Honorable Chairman"),
                    ("ebs", "EBS"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
