# Generated by Django 5.0.3 on 2024-04-18 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0004_contact_is_existing_extraattachment_is_existing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="next_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rev_nodes",
                to="pms.party",
            ),
        ),
    ]
