# Generated by Django 5.0.3 on 2024-04-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0005_party_next_node"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditlimit",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("archived", "Archived"),
                    ("not_required", "Not Required"),
                ],
                default="draft",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("archived", "Archived"),
                    ("not_required", "Not Required"),
                ],
                default="draft",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="shiplocation",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("archived", "Archived"),
                    ("not_required", "Not Required"),
                ],
                default="submitted",
                max_length=255,
            ),
        ),
    ]
