# Generated by Django 5.0.4 on 2024-04-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0007_alter_party_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="remarks",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
