# Generated by Django 5.0.4 on 2024-04-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0008_alter_party_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditlimit",
            name="remarks",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="shiplocation",
            name="recommended_delivery_addr",
            field=models.CharField(
                max_length=500, verbose_name="Recommended Delivery Address"
            ),
        ),
    ]
