# Generated by Django 5.0.4 on 2024-05-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0009_alter_creditlimit_remarks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="history_current_stage",
            field=models.CharField(
                blank=True,
                max_length=88,
                null=True,
                verbose_name="History Current Stage",
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="history_current_step",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="History Current Step"
            ),
        ),
    ]
