# Generated by Django 5.0.4 on 2024-05-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0010_party_history_current_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiplocation",
            name="authorization_letter",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Authorization Letter",
            ),
        ),
        migrations.AddField(
            model_name="shiplocation",
            name="authorization_letter_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="ship_location_applications/",
                verbose_name="Authorization Letter / Any Reference",
            ),
        ),
        migrations.AlterField(
            model_name="shiplocation",
            name="wo_po_mou_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="ship_location_applications/",
                verbose_name="WO/PO/NOA/RFQ/MOU",
            ),
        ),
    ]
