# Generated by Django 5.0.4 on 2024-05-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0011_shiplocation_authorization_letter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditlimit",
            name="approved_limit_wcl",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=34,
                null=True,
                verbose_name="Approved Limit WCL",
            ),
        ),
        migrations.AlterField(
            model_name="creditlimit",
            name="approved_limit_wdc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=34,
                null=True,
                verbose_name="Approved Limit WDC",
            ),
        ),
        migrations.AlterField(
            model_name="creditlimit",
            name="proposed_limit_wcl",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=34,
                null=True,
                verbose_name="Proposed Limit WCL",
            ),
        ),
        migrations.AlterField(
            model_name="creditlimit",
            name="proposed_limit_wdc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=34,
                null=True,
                verbose_name="Proposed Limit WDC",
            ),
        ),
        migrations.AlterField(
            model_name="creditlimitdetail",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=34),
        ),
    ]
