# Generated by Django 5.0.4 on 2024-05-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0012_alter_creditlimit_approved_limit_wcl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditlimit",
            name="party_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="creditlimit",
            name="status",
            field=models.CharField(
                choices=[
                    ("init", "Init"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("archived", "Archived"),
                    ("not_required", "Not Required"),
                ],
                default="init",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="creditlimit",
            name="witp_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="party",
            name="status",
            field=models.CharField(
                choices=[
                    ("init", "Init"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("archived", "Archived"),
                    ("not_required", "Not Required"),
                ],
                default="draft",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="shiplocation",
            name="status",
            field=models.CharField(
                choices=[
                    ("init", "Init"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("archived", "Archived"),
                    ("not_required", "Not Required"),
                ],
                default="submitted",
                max_length=255,
            ),
        ),
    ]
