# Generated by Django 5.0.4 on 2024-05-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0013_alter_creditlimit_party_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiplocation",
            name="default_addr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
