# Generated by Django 5.0.4 on 2024-05-27 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dropdown_repository", "0009_businesstypelov_partycategorylov_business_type"),
        ("pms", "0014_shiplocation_default_addr"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="business_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dropdown_repository.businesstypelov",
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="party",
            name="is_tenderable",
            field=models.BooleanField(
                default=False, verbose_name="Party is Tenderable ?"
            ),
        ),
        migrations.AlterField(
            model_name="partydealing",
            name="mou",
            field=models.CharField(
                blank=True,
                max_length=99,
                null=True,
                unique=True,
                verbose_name="MOU/PO/NOA/RFQ",
            ),
        ),
    ]
