# Generated by Django 5.0.4 on 2024-05-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0015_party_business_type_party_email_party_is_tenderable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditlimit",
            name="approved_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cod", "COD"),
                    ("7_days", "7 Days"),
                    ("15_days", "15 Days"),
                    ("30_days", "30 Days"),
                ],
                default=None,
                help_text="Credit Monitoring Approval Field !",
                max_length=88,
                null=True,
                verbose_name="Limit Application approved for",
            ),
        ),
    ]
