# Generated by Django 5.0.4 on 2024-06-02 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dropdown_repository", "0009_businesstypelov_partycategorylov_business_type"),
        ("pms", "0016_creditlimit_approved_range"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guarantee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=99,
                        null=True,
                        verbose_name="BG/PG Number",
                    ),
                ),
                ("amount", models.FloatField(default=0, verbose_name="Amount")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="attachments/gurantee_collections",
                        verbose_name="Security Cheque Image",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="Issue Date"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="Expiry Date"
                    ),
                ),
                (
                    "account_of",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=99,
                        null=True,
                        verbose_name="Account Of",
                    ),
                ),
                (
                    "issuer_bank",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dropdown_repository.bankissuerlov",
                        verbose_name="Bank Name",
                    ),
                ),
                (
                    "issuer_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dropdown_repository.branchissuerbanklov",
                        verbose_name="Branch Name",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guarantee_collections",
                        to="pms.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guarantee",
                "verbose_name_plural": "📜 Guarantee Collections",
                "db_table": "pms_guarantee_store",
            },
        ),
    ]
