# Generated by Django 5.0.4 on 2024-06-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0017_guarantee"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
    ]
