# Generated by Django 5.0.4 on 2024-06-02 09:28

from django.db import migrations, models

import pms.models.party_attachment


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0018_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="partyattachment",
            name="expiry_date_general_attachment",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Expiry Date for Attachment(If Applicable)",
            ),
        ),
        migrations.AddField(
            model_name="partyattachment",
            name="general_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=pms.models.party_attachment.upload_to_dir,
            ),
        ),
    ]
