# Generated by Django 5.0.6 on 2024-06-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0020_party_ugc_certificate_file_party_ugc_certificate_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="trade_license",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Trade License"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="trade_license_expires",
            field=models.DateField(
                blank=True, null=True, verbose_name="Trade License Expires"
            ),
        ),
    ]
