# Generated by Django 5.0.6 on 2024-06-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0021_alter_party_trade_license_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="trade_license_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="attachments/party",
                verbose_name="Trade License",
            ),
        ),
    ]
