# Generated by Django 5.0.6 on 2024-06-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0022_alter_party_trade_license_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="tin_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="TIN Number"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="trade_license_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="attachments/party",
                verbose_name="Trade License File",
            ),
        ),
    ]
