# Generated by Django 5.0.6 on 2024-06-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0023_alter_party_tin_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditlimit",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("incharge", "Incharge"),
                    ("dhos", "DHOS"),
                    ("credit_monitoring", "Credit Monitoring"),
                    ("logistics", "Logistic & Order Management"),
                    ("cbo", "Chief Business Officer"),
                    ("amd", "Additional Managing Director"),
                    ("chairman", "Honorable Chairman"),
                    ("ebs", "EBS"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("incharge", "Incharge"),
                    ("dhos", "DHOS"),
                    ("credit_monitoring", "Credit Monitoring"),
                    ("logistics", "Logistic & Order Management"),
                    ("cbo", "Chief Business Officer"),
                    ("amd", "Additional Managing Director"),
                    ("chairman", "Honorable Chairman"),
                    ("ebs", "EBS"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partydealing",
            name="mou",
            field=models.CharField(
                blank=True, max_length=99, null=True, verbose_name="MOU/PO/NOA/RFQ"
            ),
        ),
        migrations.AlterField(
            model_name="shiplocation",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("incharge", "Incharge"),
                    ("dhos", "DHOS"),
                    ("credit_monitoring", "Credit Monitoring"),
                    ("logistics", "Logistic & Order Management"),
                    ("cbo", "Chief Business Officer"),
                    ("amd", "Additional Managing Director"),
                    ("chairman", "Honorable Chairman"),
                    ("ebs", "EBS"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
