# Generated by Django 5.0.6 on 2024-08-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0025_alter_party_bin_number_alter_party_bin_number_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="is_ebs_imported_party",
            field=models.BooleanField(
                default=False, verbose_name="Is imported From Oracle DB ?"
            ),
        ),
    ]
