# Generated by Django 5.0.6 on 2024-08-20 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0025_alter_party_bin_number_alter_party_bin_number_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditlimit",
            name="ebs_info_pulled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="creditlimit",
            name="grade",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Grade"
            ),
        ),
        migrations.AddField(
            model_name="creditlimit",
            name="invoice_due_max_days",
            field=models.IntegerField(default=99999999),
        ),
        migrations.AddField(
            model_name="creditlimit",
            name="party_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Party Address"
            ),
        ),
        migrations.AddField(
            model_name="creditlimit",
            name="party_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Party Status"
            ),
        ),
        migrations.AddField(
            model_name="creditlimitdetail",
            name="judicial_stamp",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="credit_limit_applications/",
                verbose_name="Judicial Stamp",
            ),
        ),
        migrations.CreateModel(
            name="EbsCollectionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", models.CharField(max_length=88)),
                ("party_id", models.CharField(max_length=88)),
                ("account_number", models.CharField(max_length=88)),
                ("org_type", models.CharField(max_length=88)),
                ("average_coll_ratio", models.FloatField(default=0.0)),
                (
                    "avg_receipt_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=34),
                ),
                (
                    "avg_sale_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=34),
                ),
                ("last_sale_date", models.DateTimeField(blank=True, null=True)),
                ("last_receipt_date", models.DateTimeField(blank=True, null=True)),
                (
                    "opening_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=34),
                ),
                (
                    "closing_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=34),
                ),
                (
                    "total_sales_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=34),
                ),
                (
                    "total_receipt_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=34),
                ),
                (
                    "credit_limit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_details",
                        to="pms.creditlimit",
                    ),
                ),
            ],
            options={
                "verbose_name": "EBS Collection Detail",
                "verbose_name_plural": "📤 EBS Collection Details",
                "db_table": "pms_ebs_collection_detail",
            },
        ),
    ]
