# Generated by Django 5.0.6 on 2024-08-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0026_creditlimit_ebs_info_pulled_creditlimit_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="is_ebs_imported_party",
            field=models.BooleanField(
                default=False, verbose_name="Is imported From Oracle DB ?"
            ),
        ),
    ]
