# Generated by Django 5.0.6 on 2024-08-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0027_party_is_ebs_imported_party"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditlimitdetail",
            name="judicial_stamp",
        ),
        migrations.AddField(
            model_name="creditlimit",
            name="judicial_stamp",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="credit_limit_applications/",
                verbose_name="Judicial Stamp",
            ),
        ),
    ]
