# Generated by Django 5.0.6 on 2024-08-24 11:55

from django.db import migrations, models

import pms.models.party_attachment


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0028_remove_creditlimitdetail_judicial_stamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditlimit",
            name="status",
            field=models.CharField(
                choices=[
                    ("init", "Init"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("archived", "Archived"),
                    ("processing", "Processing"),
                    ("not_required", "Not Required"),
                ],
                default="init",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="status",
            field=models.CharField(
                choices=[
                    ("init", "Init"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("archived", "Archived"),
                    ("processing", "Processing"),
                    ("not_required", "Not Required"),
                ],
                default="draft",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="partyattachment",
            name="party_authorization_letter",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=pms.models.party_attachment.upload_to_dir,
            ),
        ),
        migrations.AlterField(
            model_name="shiplocation",
            name="status",
            field=models.CharField(
                choices=[
                    ("init", "Init"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("archived", "Archived"),
                    ("processing", "Processing"),
                    ("not_required", "Not Required"),
                ],
                default="submitted",
                max_length=255,
            ),
        ),
    ]
