# Generated by Django 5.0.1 on 2024-01-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hod_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="hod_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="supervisor_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="supervisor_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
