# Generated by Django 5.0.4 on 2024-04-30 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_users", "0002_user_hod_id_user_hod_name_user_supervisor_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codename",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Code Name"
                    ),
                ),
                (
                    "viewname",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="View Name"
                    ),
                ),
            ],
            options={
                "db_table": "oss_user_roles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Amd",
        ),
        migrations.DeleteModel(
            name="Cbo",
        ),
        migrations.DeleteModel(
            name="EbsUser",
        ),
        migrations.DeleteModel(
            name="Incharge",
        ),
        migrations.DeleteModel(
            name="Management",
        ),
        migrations.DeleteModel(
            name="Salesman",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("can_recommend_salesperson", "Can Recommend Sales Person"),
                    ("has_pms_access", "Has PMS access"),
                    ("has_cpq_access", "Has CPQ access"),
                )
            },
        ),
        migrations.AddField(
            model_name="role",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_%(class)s_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_by_%(class)s_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth_users.role",
            ),
        ),
    ]
