# Generated by Django 5.0.4 on 2024-04-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_users", "0003_role_delete_amd_delete_cbo_delete_ebsuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
