# Generated by Django 5.0.6 on 2024-08-22 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="contract",
        ),
        migrations.AddField(
            model_name="payment",
            name="tender",
            field=models.ForeignKey(
                default="d0909f55-72c9-4bfa-a8e8-122cf6069440",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="tms.tender",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendor",
            name="tender",
            field=models.ForeignKey(
                default="d0909f55-72c9-4bfa-a8e8-122cf6069440",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor",
                to="tms.tender",
            ),
            preserve_default=False,
        ),
    ]
