# Generated by Django 5.0.6 on 2024-08-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0002_remove_payment_contract_remove_vendor_contract_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participantbid",
            old_name="bidinng_price",
            new_name="biding_price",
        ),
    ]
