# Generated by Django 5.0.6 on 2024-08-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0003_rename_bidinng_price_participantbid_biding_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="l1_breakdown",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="l2_breakdown",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
