# Generated by Django 5.0.6 on 2024-08-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0004_product_l1_breakdown_product_l2_breakdown"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="competitor_specification",
        ),
        migrations.RemoveField(
            model_name="product",
            name="required_specification",
        ),
        migrations.RemoveField(
            model_name="product",
            name="walton_specification",
        ),
    ]
