# Generated by Django 5.0.6 on 2024-08-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0005_remove_product_competitor_specification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="walton_price",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
