# Generated by Django 5.0.6 on 2024-08-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0006_product_walton_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="analytics_note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
