# Generated by Django 5.0.6 on 2024-08-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0007_tender_analytics_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractagreement",
            name="is_pg_released",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
