# Generated by Django 5.0.6 on 2024-08-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0008_alter_contractagreement_is_pg_released"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="l1_breakdown",
            new_name="lower_one_breakdown",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="l2_breakdown",
            new_name="lower_two_breakdown",
        ),
    ]
