# Generated by Django 5.0.6 on 2024-08-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0009_rename_l1_breakdown_product_lower_one_breakdown_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productspacification",
            name="compettitors_spacification",
        ),
        migrations.AddField(
            model_name="productspacification",
            name="compettitors_spacification_one",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Compettitors One Offered Spacification",
            ),
        ),
        migrations.AddField(
            model_name="productspacification",
            name="compettitors_spacification_two",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Compettitors Two Offered Spacification",
            ),
        ),
    ]
