# Generated by Django 5.0.6 on 2024-08-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0010_remove_productspacification_compettitors_spacification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractagreement",
            name="contract_agreement_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractagreement",
            name="delivery_deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
