# Generated by Django 5.0.6 on 2024-08-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0011_alter_contractagreement_contract_agreement_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_reviewed",
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
    ]
