# Generated by Django 5.0.6 on 2024-08-27 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0013_remove_product_lower_one_breakdown_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productanalysis",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_analysis",
                to="tms.product",
            ),
        ),
    ]
