# Generated by Django 5.0.6 on 2024-08-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0014_alter_productanalysis_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="kam_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="procurring_entity",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
