# Generated by Django 5.0.6 on 2024-08-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0016_remove_notificationofaward_earliest_bg_released_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="earliestbgreleasedate",
            name="bg_released_status",
        ),
        migrations.RemoveField(
            model_name="notificationofaward",
            name="bg_released_date",
        ),
        migrations.RemoveField(
            model_name="notificationofaward",
            name="is_bg_released",
        ),
        migrations.AddField(
            model_name="earliestbgreleasedate",
            name="is_bg_released",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
