# Generated by Django 5.0.6 on 2024-08-29 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0018_bgreleaseddate_delete_earliestbgreleasedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bgreleaseddate",
            name="tender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bg_released_date",
                to="tms.tender",
            ),
        ),
    ]
