# Generated by Django 5.0.6 on 2024-08-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0019_alter_bgreleaseddate_tender"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="bg_released_status",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
