# Generated by Django 5.0.6 on 2024-08-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0021_remove_contractagreement_earliest_pg_released_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("BG", "BG"),
                    ("PG", "PG"),
                    ("NOA ACCEPTANCE DEADLINE", "NOA ACCEPTANCE DEADLINE"),
                    ("CONTRACT AGREEMENT DEADLINE", "CONTRACT AGREEMENT DEADLINE"),
                    ("COMPLETION CERTIFICATE", "COMPLETION CERTIFICATE"),
                    ("DELIVERY DEADLINE", "DELIVERY DEADLINE"),
                ],
                max_length=50,
            ),
        ),
    ]
