# Generated by Django 5.1 on 2024-09-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0022_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="probable_cost_breakdown_one",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="probable_cost_breakdown_two",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
