# Generated by Django 5.1 on 2024-09-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0023_tender_probable_cost_breakdown_one_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="is_bi_analysis_done",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
