# Generated by Django 5.1 on 2024-09-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0024_tender_is_bi_analysis_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="analytics_note",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="probable_cost_breakdown_one",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="probable_cost_breakdown_two",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
