# Generated by Django 5.0.4 on 2024-04-30 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth_users", "0003_role_delete_amd_delete_cbo_delete_ebsuser_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codename",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Code Name"
                    ),
                ),
                (
                    "viewname",
                    models.CharField(max_length=255, verbose_name="View Name"),
                ),
                ("icon", models.TextField(blank=True, max_length=255, null=True)),
                ("path", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_by_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submenus",
                        to="menu.menu",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        related_name="menus",
                        to="auth_users.role",
                        verbose_name="Access Role",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_by_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "OSS Menus",
                "db_table": "oss_menus",
                "ordering": ["-created_at"],
            },
        ),
    ]
