# Generated by Django 5.0.4 on 2024-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="icon",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
