# Generated by Django 5.0.6 on 2024-07-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_alter_menu_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="icon",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
