# Generated by Django 5.0.1 on 2024-01-27 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dropdown_repository", "0002_divisionlov_districtlov"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankissuerlov",
            options={"verbose_name": "Bank", "verbose_name_plural": "Banks"},
        ),
        migrations.AlterModelOptions(
            name="branchissuerbanklov",
            options={"verbose_name": "Branch", "verbose_name_plural": "Branches"},
        ),
        migrations.AlterModelOptions(
            name="businesszonelov",
            options={
                "verbose_name": "Business Zone",
                "verbose_name_plural": "Business Zones",
            },
        ),
        migrations.AlterModelOptions(
            name="districtlov",
            options={"verbose_name": "District", "verbose_name_plural": "Districts"},
        ),
        migrations.AlterModelOptions(
            name="divisionlov",
            options={"verbose_name": "Division", "verbose_name_plural": "Divisions"},
        ),
        migrations.AlterModelOptions(
            name="partycategorylov",
            options={
                "verbose_name": "Party Category",
                "verbose_name_plural": "Party Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="policestationlov",
            options={
                "verbose_name": "Police Station",
                "verbose_name_plural": "Police Stations",
            },
        ),
        migrations.RemoveField(
            model_name="businesszonelov",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="businesszonelov",
            name="name",
        ),
        migrations.AddField(
            model_name="businesszonelov",
            name="district",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dropdown_repository.districtlov",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="businesszonelov",
            name="division",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dropdown_repository.divisionlov",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="divisionlov",
            name="bn_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="divisionlov",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="divisionlov",
            name="long",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="districtlov",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dropdown_repository.divisionlov",
            ),
        ),
    ]
