# Generated by Django 5.0.1 on 2024-01-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dropdown_repository", "0003_alter_bankissuerlov_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divisionlov",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="divisionlov",
            name="long",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
