# Generated by Django 5.0.1 on 2024-01-27 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dropdown_repository", "0004_alter_divisionlov_lat_alter_divisionlov_long"),
    ]

    operations = [
        migrations.AddField(
            model_name="policestationlov",
            name="district",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dropdown_repository.districtlov",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policestationlov",
            name="division",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dropdown_repository.divisionlov",
            ),
            preserve_default=False,
        ),
    ]
