# Generated by Django 5.0.1 on 2024-01-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dropdown_repository",
            "0005_policestationlov_district_policestationlov_division",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="policestationlov",
            name="phone",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
