# Generated by Django 5.0.1 on 2024-01-28 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dropdown_repository", "0007_remove_policestationlov_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="policestationlov",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dropdown_repository.districtlov",
            ),
        ),
        migrations.AlterField(
            model_name="policestationlov",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dropdown_repository.divisionlov",
            ),
        ),
    ]
