# Generated by Django 5.0.6 on 2024-08-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dropdown_repository", "0009_businesstypelov_partycategorylov_business_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="partycategorylov",
            name="codename",
            field=models.CharField(
                default="NA", max_length=255, verbose_name="Code Name"
            ),
        ),
    ]
